### ISSUE TITLE
Can't wait for a single task inside a thread pool

### ISSUE THREAD

**Issue by marllon** [marllon/java-multi-task-swing#1]
Normal execution:

![normal_execution](https://user-images.githubusercontent.com/4899441/93671498-ee0c6d00-fa79-11ea-8df3-795d865c5b65.gif)

After adding a Thread.sleep inside `WorkerDoSomething`

![sleep_execution](https://user-images.githubusercontent.com/4899441/93671503-f49ae480-fa79-11ea-8e64-639423e48a99.gif)

**Comment by javimolla** [comment]
Even with very small (1ms) sleep time, given the huge amount resulting from `randomInt(10000000, 1000000000)`, it takes forever to progress

Simply changing the `randomNumber` initialization and the sleep time to something like `randomInt(10000, 100000)` and `Thread.sleep(randomInt(10, 50));`, shows progress again

**Comment by marllon** [comment]
> Even with very small (1ms) sleep time, given the huge amount resulting from `randomInt(10000000, 1000000000)`, it takes forever to progress
> 
> Simply changing the `randomNumber` initialization and the sleep time to something like `randomInt(10000, 100000)` and `Thread.sleep(randomInt(10, 50));`, shows progress again

You are correct. There is no bug after all. Thanks!
